/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pav15p' at '13/04/16 19:55' with Gradle 2.12
 *
 * @author pav15p, @date 13/04/16 19:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
